def config = readYaml text: "${env.PIPELINE_CONFIG}"
pipeline {
  agent any
  stages {
    stage("run run.sh") {
      steps {
        echo "Script to run: ${config.script_to_run}"
        sh "./${config.script_to_run}"
      }
    }
  }
}
